backend:
  name: git-gateway
  branch: main
media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "catalog"
    label: "Catalog"
    files:
      - file: "data/items.json"
        label: "Products"
        name: "products"
        fields:
          - label: "Products"
            name: "products"
            widget: "list"
            summary: "{{fields.brand}} • {{fields.title}}"
            fields:
              - {label: "Slug", name: "slug", widget: "string"}
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Brand", name: "brand", widget: "string"}
              - {label: "Category", name: "category", widget: "string"}
              - {label: "Color", name: "color", widget: "string", required: false}
              - {label: "Material", name: "material", widget: "string", required: false}
              - {label: "Price (USD)", name: "price", widget: "number", required: false, value_type: "float", min: 0}
              - {label: "Tags", name: "tags", widget: "list", required: false}
              - label: "Images"
                name: "images"
                widget: "list"
                fields:
                  - {label: "URL", name: "url", widget: "string"}
                  - {label: "Alt", name: "alt", widget: "string", required: false}
              - {label: "Video URL", name: "video", widget: "string", required: false}
              - {label: "Description", name: "description", widget: "text", required: false}
